export const PARTIDOS_POR_JORNADA = {
  "jornada-1": [
    { id: 1, local: "México", visitante: "Sudáfrica" },
    { id: 2, local: "Corea del Sur", visitante: "República Checa" },
    { id: 3, local: "Canadá", visitante: "Bosnia y Herzegovina" },
    { id: 4, local: "Estados Unidos", visitante: "Paraguay" },
    { id: 5, local: "Qatar", visitante: "Suiza" },
    { id: 6, local: "Haití", visitante: "Escocia" },
    { id: 7, local: "Brasil", visitante: "Marruecos" },
    { id: 8, local: "Australia", visitante: "Turquía" },
    { id: 9, local: "Costa de Marfil", visitante: "Ecuador" },
    { id: 10, local: "Alemania", visitante: "Curazao" },
    { id: 11, local: "Países Bajos", visitante: "Japón" },
    { id: 12, local: "Suecia", visitante: "Túnez" },
    { id: 13, local: "España", visitante: "Cabo Verde" },
    { id: 14, local: "Bélgica", visitante: "Egipto" },
    { id: 15, local: "Arabia Saudita", visitante: "Uruguay" },
    { id: 16, local: "Irán", visitante: "Nueva Zelanda" },
    { id: 17, local: "Francia", visitante: "Senegal" },
    { id: 18, local: "Irak", visitante: "Noruega" },
    { id: 19, local: "Argentina", visitante: "Argelia" },
    { id: 20, local: "Austria", visitante: "Jordania" },
    { id: 21, local: "Portugal", visitante: "RD Congo" },
    { id: 22, local: "Inglaterra", visitante: "Croacia" },
    { id: 23, local: "Ghana", visitante: "Panamá" },
    { id: 24, local: "Uzbekistán", visitante: "Colombia" },
  ],

  "jornada-2": [
    { id: 1, local: "Chequia", visitante: "Sudáfrica" },
    { id: 2, local: "Suiza", visitante: "Bosnia y Herzegovina" },
    { id: 3, local: "Canadá", visitante: "Catar" },
    { id: 4, local: "México", visitante: "Corea del Sur" },
    { id: 5, local: "Estados Unidos", visitante: "Australia" },
    { id: 6, local: "Escocia", visitante: "Marruecos" },
    { id: 7, local: "Brasil", visitante: "Haití" },
    { id: 8, local: "Turquía", visitante: "Paraguay" },
    { id: 9, local: "Países Bajos", visitante: "Suecia" },
    { id: 10, local: "Alemania", visitante: "Costa de Marfil" },
    { id: 11, local: "Ecuador", visitante: "Curazao" },
    { id: 12, local: "Túnez", visitante: "Japón" },
    { id: 13, local: "España", visitante: "Arabia Saudita" },
    { id: 14, local: "Bélgica", visitante: "Irán" },
    { id: 15, local: "Uruguay", visitante: "Cabo Verde" },
    { id: 16, local: "Nueva Zelanda", visitante: "Egipto" },
    { id: 17, local: "Argentina", visitante: "Austria" },
    { id: 18, local: "Francia", visitante: "Irak" },
    { id: 19, local: "Noruega", visitante: "Senegal" },
    { id: 20, local: "Jordania", visitante: "Argelia" },
    { id: 21, local: "Portugal", visitante: "Uzbekistán" },
    { id: 22, local: "Inglaterra", visitante: "Ghana" },
    { id: 23, local: "Panamá", visitante: "Croacia" },
    { id: 24, local: "Colombia", visitante: "R.D. Congo" },
  ],

  "jornada-3": [
  { id: 1, local: "Suiza", visitante: "Canadá" },
  { id: 2, local: "Bosnia y Herzegovina", visitante: "Catar" },
  { id: 3, local: "Marruecos", visitante: "Haití" },
  { id: 4, local: "Escocia", visitante: "Brasil" },
  { id: 5, local: "Sudáfrica", visitante: "Corea del Sur" },
  { id: 6, local: "Chequia", visitante: "México" },

  { id: 7, local: "Curazao", visitante: "Costa de Marfil" },
  { id: 8, local: "Ecuador", visitante: "Alemania" },
  { id: 9, local: "Túnez", visitante: "Países Bajos" },
  { id: 10, local: "Japón", visitante: "Suecia" },
  { id: 11, local: "Turquía", visitante: "Estados Unidos" },
  { id: 12, local: "Paraguay", visitante: "Australia" },

  { id: 13, local: "Noruega", visitante: "Francia" },
  { id: 14, local: "Senegal", visitante: "Irak" },
  { id: 15, local: "Cabo Verde", visitante: "Arabia Saudita" },
  { id: 16, local: "Uruguay", visitante: "España" },
  { id: 17, local: "Nueva Zelanda", visitante: "Bélgica" },
  { id: 18, local: "Egipto", visitante: "Irán" },

  { id: 19, local: "Panamá", visitante: "Inglaterra" },
  { id: 20, local: "Croacia", visitante: "Ghana" },
  { id: 21, local: "Colombia", visitante: "Portugal" },
  { id: 22, local: "RD Congo", visitante: "Uzbekistán" },
  { id: 23, local: "Argelia", visitante: "Austria" },
  { id: 24, local: "Jordania", visitante: "Argentina" },
],

"16vos": [
  { id: 1, local: "Sudáfrica", visitante: "Canadá" },
  { id: 2, local: "Brasil", visitante: "Japón" },
  { id: 3, local: "Alemania", visitante: "Paraguay" },
  { id: 4, local: "Países Bajos", visitante: "Marruecos" },
  { id: 5, local: "Costa de Marfil", visitante: "Noruega" },
  { id: 6, local: "Francia", visitante: "Suecia" },
  { id: 7, local: "México", visitante: "Ecuador" },
  { id: 8, local: "Inglaterra", visitante: "R.D. Congo" },
  { id: 9, local: "Bélgica", visitante: "Senegal" },
  { id: 10, local: "Estados Unidos", visitante: "Bosnia y Herzegovina" },
  { id: 11, local: "España", visitante: "Austria" },
  { id: 12, local: "Portugal", visitante: "Croacia" },
  { id: 13, local: "Suiza", visitante: "Argelia" },
  { id: 14, local: "Australia", visitante: "Egipto" },
  { id: 15, local: "Argentina", visitante: "Cabo Verde" },
  { id: 16, local: "Colombia", visitante: "Ghana" },
],
} as const;

export function getPartidos(jornadaId: string) {
  return PARTIDOS_POR_JORNADA[
    jornadaId as keyof typeof PARTIDOS_POR_JORNADA
  ] || [];
}